import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient, createAdminClient } from "@/lib/supabase/server";
import { getResend, FROM_EMAIL } from "@/lib/resend";
import type { Profile, Church } from "@/lib/types";

const schema = z.object({
  email: z.string().email(),
});

export async function POST(request: Request) {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const data = schema.parse(body);

    // Fetch caller profile
    const { data: profile } = await supabase
      .from("profiles")
      .select("role, church_id, full_name")
      .eq("id", user.id)
      .single();

    const p = profile as Pick<Profile, "role" | "church_id" | "full_name"> | null;

    if (!p || !["church_admin", "super_admin"].includes(p.role)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    if (!p.church_id) {
      return NextResponse.json({ error: "No church associated" }, { status: 400 });
    }

    // Fetch church name for the email
    const adminClient = createAdminClient();
    const { data: church } = await adminClient
      .from("churches")
      .select("name")
      .eq("id", p.church_id)
      .single();

    const churchName = (church as Pick<Church, "name"> | null)?.name ?? "your church";

    // Insert invitation — token auto-generated by DB default
    const { data: invite, error: insertError } = await supabase
      .from("invitations")
      .insert({
        church_id: p.church_id,
        email: data.email,
        invited_by: user.id,
      })
      .select("token")
      .single();

    if (insertError) throw insertError;

    const inviteUrl = `${process.env.NEXT_PUBLIC_SITE_URL ?? "https://ourdailybread.club"}/join/${invite.token}`;

    // Send invite email
    await getResend().emails.send({
      from: FROM_EMAIL,
      to: data.email,
      subject: `You're invited to join ${churchName} on Our Daily Bread`,
      html: `
        <div style="font-family: Georgia, serif; max-width: 560px; margin: 0 auto; color: #1a1a1a;">
          <h2 style="color: #C8973A;">You've been invited! 🍞</h2>
          <p><strong>${p.full_name}</strong> has invited you to join <strong>${churchName}</strong> on <em>Our Daily Bread</em> — a platform helping church communities track bread sales for fundraising.</p>
          <p style="margin: 24px 0;">
            <a href="${inviteUrl}" style="background: #C8973A; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold;">Accept Invitation</a>
          </p>
          <p style="color: #888; font-size: 14px;">This invitation expires in 7 days. If you didn't expect this, you can safely ignore it.</p>
        </div>
      `,
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    if (err instanceof z.ZodError) {
      return NextResponse.json({ error: "Invalid email address" }, { status: 400 });
    }
    console.error("Invitations API error:", err);
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
